#!/usr/bin/env bash
set -euo pipefail

# AI Learning Engineer — Daily Digest Generator
# Runs via GitHub Actions, calls Claude API to generate daily content

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
TODAY=$(date -u +"%Y-%m-%d")
OUTPUT_DIR="$ROOT_DIR/output/ai-learning-engineer"
OUTPUT_FILE="$OUTPUT_DIR/$TODAY.html"
LATEST_FILE="$OUTPUT_DIR/latest.html"
PROMPT_FILE="$ROOT_DIR/tasks/ai-learning-engineer/prompt.md"

mkdir -p "$OUTPUT_DIR"

echo "Generating AI Learning Engineer digest for $TODAY..."

# Read the prompt
SYSTEM_PROMPT=$(cat "$PROMPT_FILE")

# Build the HTML template wrapper
read -r -d '' HTML_PREFIX << 'HTMLEOF' || true
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>AI Learning Engineer — DATE_PLACEHOLDER</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500;600&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="../../shared/css/style.css">
</head>
<body>
  <div class="container">
    <a href="../../index.html" class="nav-back">&larr; Back to Dashboard</a>
    <header class="site-header">
      <div style="display:flex;align-items:center;gap:var(--space-4)">
        <div class="card__icon card__icon--ai" style="width:48px;height:48px;font-size:1.5rem;">&#9883;</div>
        <div>
          <h1 class="site-header__title">AI Learning Engineer</h1>
          <p class="site-header__subtitle">Your 10-minute daily AI briefing</p>
        </div>
      </div>
      <div class="site-header__date">DATE_PLACEHOLDER</div>
    </header>
HTMLEOF

read -r -d '' HTML_SUFFIX << 'HTMLEOF' || true
    <footer class="site-footer">
      AI Schedules &middot; Generated by AI &middot; <a href="../../index.html">Back to Dashboard</a>
    </footer>
  </div>
</body>
</html>
HTMLEOF

HTML_PREFIX="${HTML_PREFIX//DATE_PLACEHOLDER/$TODAY}"
HTML_SUFFIX="${HTML_SUFFIX//DATE_PLACEHOLDER/$TODAY}"

# Call Claude API
USER_MESSAGE="Today is $TODAY. Generate today's AI Learning Engineer daily digest. Output ONLY the inner HTML content (the sections between header and footer — do not include <!DOCTYPE>, <html>, <head>, <body>, or wrapper tags). Use CSS classes from the shared design system (content-item, content-item__title, content-item__body, tag, section-title, etc.)."

RESPONSE=$(curl -s https://api.anthropic.com/v1/messages \
  -H "x-api-key: $ANTHROPIC_API_KEY" \
  -H "anthropic-version: 2023-06-01" \
  -H "content-type: application/json" \
  -d "$(jq -n \
    --arg system "$SYSTEM_PROMPT" \
    --arg user "$USER_MESSAGE" \
    '{
      model: "claude-sonnet-4-20250514",
      max_tokens: 4096,
      system: $system,
      messages: [{role: "user", content: $user}]
    }')")

# Extract content from response
CONTENT=$(echo "$RESPONSE" | jq -r '.content[0].text // empty')

if [ -z "$CONTENT" ]; then
  echo "ERROR: Failed to generate content."
  echo "API Response: $RESPONSE"
  exit 1
fi

# Assemble full HTML
{
  echo "$HTML_PREFIX"
  echo "$CONTENT"
  echo "$HTML_SUFFIX"
} > "$OUTPUT_FILE"

# Copy to latest
cp "$OUTPUT_FILE" "$LATEST_FILE"

echo "Generated: $OUTPUT_FILE"
echo "Updated:   $LATEST_FILE"
