#!/usr/bin/env bash
set -euo pipefail

# AI Learning Engineer — YouTube Deep-Dive Session Generator
# Runs via GitHub Actions, calls Claude API to generate daily session content
# Reads progress.json to know which video/session to generate, updates it after

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
TODAY=$(date -u +"%Y-%m-%d")
OUTPUT_DIR="$ROOT_DIR/output/ai-learning-engineer"
OUTPUT_FILE="$OUTPUT_DIR/$TODAY.html"
LATEST_FILE="$OUTPUT_DIR/latest.html"
PROMPT_FILE="$ROOT_DIR/tasks/ai-learning-engineer/prompt.md"
PROGRESS_FILE="$ROOT_DIR/tasks/ai-learning-engineer/progress.json"

mkdir -p "$OUTPUT_DIR"

echo "Generating AI Learning Engineer session for $TODAY..."

# Read the prompt and progress
SYSTEM_PROMPT=$(cat "$PROMPT_FILE")
PROGRESS=$(cat "$PROGRESS_FILE")

# Build the HTML template wrapper
read -r -d '' HTML_PREFIX << 'HTMLEOF' || true
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>AI Learning Engineer — DATE_PLACEHOLDER</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500;600&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="../../shared/css/style.css">
</head>
<body>
  <div class="container">
    <a href="../../index.html" class="nav-back">&larr; Back to Dashboard</a>
    <header class="site-header">
      <div style="display:flex;align-items:center;gap:var(--space-4)">
        <div class="card__icon card__icon--ai" style="width:48px;height:48px;font-size:1.5rem;">&#9883;</div>
        <div>
          <h1 class="site-header__title">AI Learning Engineer</h1>
          <p class="site-header__subtitle">YouTube deep-dive learning sessions</p>
        </div>
      </div>
      <div class="site-header__date">DATE_PLACEHOLDER</div>
    </header>
HTMLEOF

read -r -d '' HTML_SUFFIX << 'HTMLEOF' || true
    <footer class="site-footer">
      AI Schedules &middot; Generated by AI &middot; <a href="../../index.html">Back to Dashboard</a>
    </footer>
  </div>
</body>
</html>
HTMLEOF

HTML_PREFIX="${HTML_PREFIX//DATE_PLACEHOLDER/$TODAY}"
HTML_SUFFIX="${HTML_SUFFIX//DATE_PLACEHOLDER/$TODAY}"

# Call Claude API with progress context
USER_MESSAGE="Today is $TODAY.

PROGRESS CONTEXT:
$PROGRESS

Generate today's AI Learning Engineer session based on the progress above. Output ONLY the inner HTML content (the sections between header and footer — do not include <!DOCTYPE>, <html>, <head>, <body>, or wrapper tags). Use CSS classes from the shared design system (content-item, content-item__title, content-item__body, tag, section-title, confidence, confidence__bar, confidence__fill, etc.).

Include the YouTube video link as a clickable anchor tag. Show a progress bar for sessions completed vs total."

RESPONSE=$(curl -s https://api.anthropic.com/v1/messages \
  -H "x-api-key: $ANTHROPIC_API_KEY" \
  -H "anthropic-version: 2023-06-01" \
  -H "content-type: application/json" \
  -d "$(jq -n \
    --arg system "$SYSTEM_PROMPT" \
    --arg user "$USER_MESSAGE" \
    '{
      model: "claude-sonnet-4-20250514",
      max_tokens: 4096,
      system: $system,
      messages: [{role: "user", content: $user}]
    }')")

# Extract content from response
CONTENT=$(echo "$RESPONSE" | jq -r '.content[0].text // empty')

if [ -z "$CONTENT" ]; then
  echo "ERROR: Failed to generate content."
  echo "API Response: $RESPONSE"
  exit 1
fi

# Assemble full HTML
{
  echo "$HTML_PREFIX"
  echo "$CONTENT"
  echo "$HTML_SUFFIX"
} > "$OUTPUT_FILE"

# Copy to latest
cp "$OUTPUT_FILE" "$LATEST_FILE"

echo "Generated: $OUTPUT_FILE"
echo "Updated:   $LATEST_FILE"

# Advance progress for next run
CURRENT_SESSION=$(echo "$PROGRESS" | jq '.current_video.current_session')
TOTAL_SESSIONS=$(echo "$PROGRESS" | jq '.current_video.total_sessions')
NEXT_SESSION=$((CURRENT_SESSION + 1))

if [ "$NEXT_SESSION" -gt "$TOTAL_SESSIONS" ]; then
  # Video complete — move to next in queue
  echo "Video complete. Moving to next in queue..."
  COMPLETED_VIDEO=$(echo "$PROGRESS" | jq '.current_video | {title, url, channel, duration, views}')
  NEXT_VIDEO=$(echo "$PROGRESS" | jq '.topic_queue[0] // empty')

  if [ -n "$NEXT_VIDEO" ] && [ "$NEXT_VIDEO" != "null" ]; then
    # Estimate sessions for next video (1 session per 20 min, minimum 1)
    NEXT_DURATION=$(echo "$NEXT_VIDEO" | jq -r '.duration')
    HOURS=$(echo "$NEXT_DURATION" | grep -oP '(\d+)h' | grep -oP '\d+' || echo "0")
    MINS=$(echo "$NEXT_DURATION" | grep -oP '(\d+)m' | grep -oP '\d+' || echo "0")
    TOTAL_MINS=$(( HOURS * 60 + MINS ))
    EST_SESSIONS=$(( (TOTAL_MINS + 19) / 20 ))
    [ "$EST_SESSIONS" -lt 1 ] && EST_SESSIONS=1

    PROGRESS=$(echo "$PROGRESS" | jq \
      --argjson completed "$COMPLETED_VIDEO" \
      --argjson next "$NEXT_VIDEO" \
      --argjson sessions "$EST_SESSIONS" \
      '.completed_videos += [$completed] |
       .current_video = ($next + {"total_sessions": $sessions, "current_session": 1, "session_plan": []}) |
       .topic_queue = .topic_queue[1:]')
  else
    # Queue empty — mark completed
    PROGRESS=$(echo "$PROGRESS" | jq \
      --argjson completed "$COMPLETED_VIDEO" \
      '.completed_videos += [$completed] |
       .current_video.current_session = .current_video.total_sessions')
  fi
else
  # Advance to next session of same video
  PROGRESS=$(echo "$PROGRESS" | jq \
    --argjson next "$NEXT_SESSION" \
    '.current_video.current_session = $next')
fi

echo "$PROGRESS" | jq '.' > "$PROGRESS_FILE"
echo "Progress updated: session $CURRENT_SESSION -> next run"
