#!/usr/bin/env bash
set -euo pipefail

# Stock Trader — Daily Market Analysis Generator
# Runs via GitHub Actions, calls Claude API to generate daily stock picks

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
TODAY=$(date -u +"%Y-%m-%d")
NOW_ET=$(TZ="America/New_York" date +"%Y-%m-%d %H:%M:%S %Z")
OUTPUT_DIR="$ROOT_DIR/output/stock-trader"
OUTPUT_FILE="$OUTPUT_DIR/$TODAY.html"
LATEST_FILE="$OUTPUT_DIR/latest.html"
PROMPT_FILE="$ROOT_DIR/tasks/stock-trader/prompt.md"

mkdir -p "$OUTPUT_DIR"

echo "Generating Stock Trader analysis for $TODAY..."

# Read the prompt
SYSTEM_PROMPT=$(cat "$PROMPT_FILE")

# Build the HTML template wrapper
read -r -d '' HTML_PREFIX << 'HTMLEOF' || true
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Stock Trader — DATE_PLACEHOLDER</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500;600&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="../../shared/css/style.css">
</head>
<body>
  <div class="container container--wide">
    <a href="../../index.html" class="nav-back">&larr; Back to Dashboard</a>
    <header class="site-header">
      <div style="display:flex;align-items:center;gap:var(--space-4)">
        <div class="card__icon card__icon--stock" style="width:48px;height:48px;font-size:1.5rem;">&#9650;</div>
        <div>
          <h1 class="site-header__title">Stock Trader</h1>
          <p class="site-header__subtitle">Pre-market analysis — Top 10 growth picks</p>
        </div>
      </div>
      <div class="site-header__date">DATE_PLACEHOLDER</div>
    </header>
HTMLEOF

read -r -d '' HTML_SUFFIX << 'HTMLEOF' || true
    <div class="disclaimer mt-8">
      <strong>Disclaimer:</strong> This report is AI-generated for educational and informational purposes only.
      It does not constitute financial advice, investment recommendations, or an offer to buy or sell securities.
      Always conduct your own research and consult a qualified financial advisor before making investment decisions.
      Past performance does not guarantee future results. Trading stocks involves risk of loss.
    </div>
    <footer class="site-footer">
      AI Schedules &middot; Generated by AI &middot; <a href="../../index.html">Back to Dashboard</a>
    </footer>
  </div>
</body>
</html>
HTMLEOF

HTML_PREFIX="${HTML_PREFIX//DATE_PLACEHOLDER/$TODAY}"
HTML_SUFFIX="${HTML_SUFFIX//DATE_PLACEHOLDER/$TODAY}"

# Call Claude API
USER_MESSAGE="Today is $TODAY. Generation timestamp: $NOW_ET. Generate today's pre-market stock analysis. For every price, percentage change, and numerical data point, include a timestamp (use the generation timestamp as the base time, in HH:MM:SS ET format) and data source using the price-meta CSS class. Output ONLY the inner HTML content (the sections between header and footer — do not include <!DOCTYPE>, <html>, <head>, <body>, or wrapper tags). Use CSS classes from the shared design system (stock-table, stock-symbol, stock-change--up, stock-change--down, confidence, confidence__bar, confidence__fill, confidence__label, content-item, section-title, tag, badge, price-meta, etc.)."

RESPONSE=$(curl -s https://api.anthropic.com/v1/messages \
  -H "x-api-key: $ANTHROPIC_API_KEY" \
  -H "anthropic-version: 2023-06-01" \
  -H "content-type: application/json" \
  -d "$(jq -n \
    --arg system "$SYSTEM_PROMPT" \
    --arg user "$USER_MESSAGE" \
    '{
      model: "claude-sonnet-4-20250514",
      max_tokens: 4096,
      system: $system,
      messages: [{role: "user", content: $user}]
    }')")

# Extract content from response
CONTENT=$(echo "$RESPONSE" | jq -r '.content[0].text // empty')

if [ -z "$CONTENT" ]; then
  echo "ERROR: Failed to generate content."
  echo "API Response: $RESPONSE"
  exit 1
fi

# Assemble full HTML
{
  echo "$HTML_PREFIX"
  echo "$CONTENT"
  echo "$HTML_SUFFIX"
} > "$OUTPUT_FILE"

# Copy to latest
cp "$OUTPUT_FILE" "$LATEST_FILE"

echo "Generated: $OUTPUT_FILE"
echo "Updated:   $LATEST_FILE"
